version: '3.4'

services:
  profductcatalogapi:
    image: profductcatalogapi:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_profductcatalogapi$
    volumes:
      - C:\Users\sankalpg\Documents\Microservices\ShoesOnContainers\ProfductCatalogAPI:/app
      - C:\Users\sankalpg\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_profductcatalogapi$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_profductcatalogapi$ bin/Debug/netcoreapp2.0/ProfductCatalogAPI.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
